// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/CommercialManagementSystem/back/internal/controller"
	"github.com/CommercialManagementSystem/back/internal/dao"
	"github.com/CommercialManagementSystem/back/internal/model"
	"github.com/CommercialManagementSystem/back/internal/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, err := InitGorm()
	if err != nil {
		return nil, nil, err
	}
	userDao := &dao.UserDao{
		DB: db,
	}
	loginModel := &model.LoginModel{
		UserDao: userDao,
	}
	login := &controller.Login{
		LoginModel: loginModel,
	}
	routerRouter := &router.Router{
		LoginAPI: login,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
	}, nil
}
